remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"
title: "Eternal Purple"
description: "A small blog from a cyber security purple teamer"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Enable grid layout for posts
collections:
  posts:
    output: true
    layout: grid

# Pagination settings
paginate: 6
paginate_path: "/page:num/"